AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - lib/tasks/**/*
    - spec/i18n_spec.rb
    - Gemfile.lock
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
