AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - lib/tasks/**/*
    - spec/i18n_spec.rb
    - Gemfile.lock
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "config/environments/**/*"
    - "spec/classes/**/*"
    - "spec/factories/**/*"
    - "spec/features/**/*"
    - "spec/helpers/**/*"
    - "spec/models/**/*"
    - "spec/requests/**/*"
    - "spec/routing/**/*"

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
