version: 2.1
jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/ruby:3.0.4-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: localhost
          PGUSER: portfolio
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: portfolio
          POSTGRES_DB: portfolio_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - run:
          name: Setup Chrome
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb
      - run:
          name: Create Directories
          command: mkdir -p test-results
      - run:
          name: Create .env
          command: cp .sample.env .env

      # Restore the dependency cache
      - restore_cache:
          keys:
            - portfolio-gemfile-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle install --deployment --jobs=4 --retry=3

      - run:
          name: Run yarn
          command: yarn

      - run:
          name: Build assets
          command: yarn build

      # Save dependency cache
      - save_cache:
          key: portfolio-gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - ~/.bundle

      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bin/setup
      - run: bundle exec bin/rails db:test:prepare
      - run:
          name: Run tests
          command: bundle exec rspec -r rspec_junit_formatter --format RspecJunitFormatter -o test-results/rspec/results.xml
      - run:
          name: Check for Insecure Gems
          command: bundle exec bin/rails bundler:audit

      - store_test_results:
          path: test-results
