---
- name: Install prerequisites
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure hostname is in the /etc/hosts file
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    state: present
    insertbefore: BOF
    line: "127.0.0.1 {{ hostname }}"

- name: Ensure sudo group is present
  ansible.builtin.group:
    name: sudo
    state: present

- name: Ensure sudo group has sudo privileges
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
