---
- name: Ensure group is present
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

- name: Allow deployment group to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%{{ group }}"
    line: "%{{ group }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Install ZSH
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Create a new user with sudo privileges
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password }}"
    state: present
    groups: "{{ group }}"
    append: true
    create_home: true
    shell: /bin/zsh

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_key }}"
