---
- name: Base server setup
  hosts: bootstrap
  become: true

  roles:
    - role: setup_system
      vars:
        hostname: portfolio

    - role: create_user
      vars:
        username: "{{ base.username }}"
        password: "{{ base.password_hash }}"
        group: "{{ base.username }}"
        ssh_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Provision Server
  hosts: normal

  roles:
    - role: timezone
      vars:
        zone_name: America/New_York
    - role: ssh
    - role: asdf
    - role: asdf_plugin
      vars:
        plugin_name: ruby
    - role: asdf_plugin
      vars:
        plugin_name: nodejs
    - role: asdf_plugin
      vars:
        plugin_name: yarn
