---
- name: Base server setup
  hosts: bootstrap
  become: true
  roles:
    - role: setup_system
      vars:
        hostname: portfolio
    - role: create_user
      vars:
        username: "{{ base.username }}"
        password: "{{ base.password_hash }}"
        group: "{{ base.username }}"
        ssh_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Provision Server
  hosts: normal
  roles:
    - role: timezone
      vars:
        zone_name: America/New_York
    - role: ssh
    - role: git
    - role: firewall
    - role: asdf
    - role: asdf_plugin
      vars:
        plugin_name: ruby
    - role: asdf_plugin
      vars:
        plugin_name: nodejs
    - role: asdf_plugin
      vars:
        plugin_name: python
    - role: asdf_plugin
      vars:
        plugin_name: yarn
    - role: postgres
    - role: nginx
    - role: edward

- name: Specific app dependencies
  hosts: normal
  roles:
    - role: app_database
    - role: app_deploy
      vars:
        app_name: portfolio
        git_url: git@github.com:edwardloveall/portfolio.git
        location: "{{ ansible_env.HOME }}/{{ app_name }}"
        blog_host: blog.edwardloveall.com
  environment:
    APPLICATION_HOST: "{{ postgres.username }}"
    ASDF_DIR: "{{ ansible_env.HOME }}/.asdf"
    PATH: "{{ ansible_env.HOME }}/.asdf/shims:{{ ansible_env.HOME }}/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:./bin"
    PGUSER: "{{ postgres.username }}"
    PGPASSWORD: "{{ postgres.password }}"
    RAILS_ENV: production
    SECRET_KEY_BASE: "{{ rails.secret }}"
