---
- name: Set timezone
  timezone:
    name: "{{ zone_name }}"
  become: true

- name: Install ntp
  ansible.builtin.apt:
    name: ntp
    state: present
  become: true

- name: Start/Enable ntp
  ansible.builtin.service:
    name: ntp
    enabled: true
    state: started
  become: true
