---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

- name: Allow ssh connections on custom port
  community.general.ufw:
    rule: allow
    to_port: "{{ ssh_port }}"
  become: true

- name: Update SSH configuration to be more secure
  ansible.builtin.lineinfile:
    dest: /lib/systemd/system/ufw.service
    regexp: "^After="
    line: "After=netfilter-persistent.service"
    state: present
  become: true

- name: Start the Firewall
  ufw:
    state: enabled
  become: true
