---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

- name: Allow ssh connections on custom port
  community.general.ufw:
    rule: allow
    to_port: "{{ ssh_port }}"
  become: true

- name: Start the Firewall
  ufw:
    state: enabled
  become: true
