---
- name: Allow ssh connections
  community.general.ufw:
    rule: allow
    name: OpenSSH
    to_port: "{{ ssh_port }}"
  become: true

- name: Start the Firewall
  ufw:
    state: enabled
  become: true
