- name: Set swap_file variable
  ansible.builtin.set_fact:
    swap_file: "{{ swap_file_path }}"

- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: Create swap file
  ansible.builtin.command: fallocate -l {{ swap_file_size }} {{ swap_file }}
  when: not swap_file_check.stat.exists
  become: true

- name: Change swap file permissions
  ansible.builtin.file:
    path: "{{ swap_file }}"
    owner: root
    group: root
    mode: 0600
  become: true

- name: Format swap file
  ansible.builtin.command: "mkswap {{ swap_file }}"
  when: not swap_file_check.stat.exists
  become: true

- name: Write swap entry in fstab
  ansible.posix.mount:
    name: none
    src: "{{ swap_file }}"
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
  become: true

- name: Turn on swap
  ansible.builtin.command: swapon -a
  when: not swap_file_check.stat.exists
  become: true

- name: Set swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
  become: true
