---
- name: Add git stable repository from PPA
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
  become: true

- name: Update apt
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install git
  ansible.builtin.apt:
    name: git
    state: latest # noqa package-latest
  become: true
