development: &default
  adapter: postgresql
  database: portfolio_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

test:
  <<: *default
  database: portfolio_test

production: &deploy
  <<: *default
  database: portfolio_production
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging:
  <<: *deploy
  database: portfolio_staging
