---
- name: install packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ asdf_packages }}"

- name: install asdf
  become: false
  ansible.builtin.git:
    clone: true
    repo: "{{ asdf_repo_url }}"
    dest: "{{ asdf_install_dir }}"
    version: "{{ asdf_version }}"
