---
- name: Copy non-https nginx configuration in place
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ app_name }}.conf"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  when: not https
  become: true

- name: Copy https nginx configuration in place
  ansible.builtin.template:
    src: nginx-https.conf.j2
    dest: "/etc/nginx/sites-available/{{ app_name }}.conf"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  when: https
  become: true

- name: Symlink site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ app_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    state: link
  become: true

- name: Remove default symlink
  ansible.builtin.file:
    dest: "/etc/nginx/sites-enabled/default"
    state: absent
  become: true

- name: Set nginx user
  ansible.builtin.lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: "^user"
    line: "user {{ user }};"
    state: present
  become: true

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: not https
  become: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: not https
  become: true
